### ISSUE TITLE
[FEATURE] Introduce 'modulesExcluded' property for ossIndexAudit

### ISSUE THREAD

**Issue by TheoLassonder** [sonatype-nexus-community/scan-gradle-plugin#109]
* **What are you trying to do?**
Run an audit in a multi project situation and wanting to exclude the dependencies for a particular sub project. That sub project has a low priority in terms of maintenance and is only used within our own network where we control the network traffic.

* **What feature or behavior is this required for?**
With the new property we would not get false positives.

* **How could we solve this issue? (Not knowing is okay!)**
The nexusIQScan already supports this setting. Add a similar setting to ossIndexAudit. Not sure where this could best be implemented in the plugin. I'm happy to write a PR if you can point me in the right direction.

cc @bhamail / @DarthHater / @guillermo-varela / @shaikhu

**Comment by guillermo-varela** [comment]
Hi @TheoLassonder!

Thanks you for your interest in this plugin :)

Currently the modules are filtered for the nexusIQScan task here:
https://github.com/sonatype-nexus-community/scan-gradle-plugin/blob/26d72015ba62185f0b2a2b833e5566f46a3203de/src/main/java/org/sonatype/gradle/plugins/scan/common/DependenciesFinder.java#L96-L97

For OSS Index that would need to be done in the stream where the projects/modules are processed:
https://github.com/sonatype-nexus-community/scan-gradle-plugin/blob/26d72015ba62185f0b2a2b833e5566f46a3203de/src/main/java/org/sonatype/gradle/plugins/scan/ossindex/OssIndexAuditTask.java#L75-L78

We're getting settings like that one from Extension classes (see [NexusIqPluginIndexExtension.java](https://github.com/sonatype-nexus-community/scan-gradle-plugin/blob/26d72015ba62185f0b2a2b833e5566f46a3203de/src/main/java/org/sonatype/gradle/plugins/scan/nexus/iq/index/NexusIqPluginIndexExtension.java#L27)) to be compatible with older Gradle versions.

For OSS Index the extension class we have the class [OssIndexPluginExtension.java](https://github.com/sonatype-nexus-community/scan-gradle-plugin/blob/main/src/main/java/org/sonatype/gradle/plugins/scan/ossindex/OssIndexPluginExtension.java)

We also prefer having unit tests for each feature introduced and the place for changes in that task would be: [OssIndexAuditTaskTest.java](https://github.com/sonatype-nexus-community/scan-gradle-plugin/blob/main/src/test/java/org/sonatype/gradle/plugins/scan/ossindex/OssIndexAuditTaskTest.java)

**Comment by TheoLassonder** [comment]
In some situations it's easier to specify which module to include, rather than which modules to exclude. How about adding a second property `modulesIncluded`? We'd apply that property before `modulesExcluded`.

I'd actually use `modulesIncluded` in the project I'm working on at the moment.

**Comment by guillermo-varela** [comment]
Hi @TheoLassonder!

That makes sense, by any chances would you be interested in submitting another PR for it?

**Comment by TheoLassonder** [comment]
Sure no problem. Can you please accept pull request #111 first?

**Comment by guillermo-varela** [comment]
> Sure no problem. Can you please accept pull request #111 first?

I was going to merge your PR, then I saw there are some tests failures: https://github.com/sonatype-nexus-community/scan-gradle-plugin/pull/111#issuecomment-1115273724

Could you please check?

**Comment by guillermo-varela** [comment]
Hi @TheoLassonder,

The PR for this feature was merged and published!

It's now available in version 2.3.0

Thank you for helping to improve this plugin 👍

**Comment by guillermo-varela** [comment]
https://github.com/sonatype-nexus-community/scan-gradle-plugin/releases/tag/2.3.0
