### ISSUE TITLE
[BUG] Latest release 2.4.0 appears to be broken

### ISSUE THREAD

**Issue by nagyesta** [sonatype-nexus-community/scan-gradle-plugin#116]
**Describe the bug**
When I try to run my CI steps on the Renovate generated branch which is updating to 2.4.0, I am getting this error:
```
* What went wrong:
A problem occurred configuring root project 'lowkey-vault'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find org.sonatype.gradle.plugins:scan-gradle-plugin:2.4.0.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/org/sonatype/gradle/plugins/scan-gradle-plugin/2.4.0/scan-gradle-plugin-2.4.0.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project : > org.sonatype.gradle.plugins.scan:org.sonatype.gradle.plugins.scan.gradle.plugin:2.4.0
```

**To Reproduce**
1. Run './gradelw build' on this branch: https://github.com/nagyesta/lowkey-vault/tree/renovate/indexscanplugin
2. See error

**Expected behavior**
The plugin is resolved and working

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Gradle Version: 7.4.2
 - JVM Version and Flavor JDK 11 Temurin
 - Nexus IQ Server Version: -
 - Version 2.4.0

**Additional context**
Not a huge issue for me, just wanted to make sure you are aware of the issue.

**Comment by kaklakariada** [comment]
I can confirm this issue. Previous version 2.3.0 works.

**Comment by guillermo-varela** [comment]
Hi @nagyesta and @kaklakariada

Thanks for letting us know about this.

Apparently the JAR file was uploaded to the Plugins portal but the POM file didn't.

While this is resolved, version 2.4.0 is available as well in Maven Central which can be setup like this:
```
buildscript {
  repositories {
    mavenCentral()
  }
  dependencies {
    classpath "org.sonatype.gradle.plugins:scan-gradle-plugin:2.4.0"
  }
}

apply plugin: "org.sonatype.gradle.plugins.scan"
```

**Comment by nagyesta** [comment]
hi @guillermo-varela ,
thank you! I am not in a hurry, the previous version is working fine. Will wait for the next release instead.

**Comment by guillermo-varela** [comment]
Version 2.4.1 has been published into the Gradle plugins portal.

In local tests the download works fine. Please let us know if there are issues using that version :)

**Comment by kaklakariada** [comment]
@guillermo-varela : thank you, 2.4.1 works :+1:
