### ISSUE TITLE
IQ Server Version

### ISSUE THREAD

**Issue by cscrbuildhp** [sonatype-nexus-community/scan-gradle-plugin#125]
How do we know which version of IQ server the plug-in supports? We currently are running 142 but get the below error when running in our Android apps now, 
*** What went wrong:
Execution failed for task ':nexusIQScan'.
> Could not scan the project: Could not validate the IQ Server version.**

User was admin for IQ

**Comment by guillermo-varela** [comment]
Hi @cscrbuildhp 

Could you please share the full stacktrace?
The message might be missleading as I have seen it even when the issue is due to connectivity.

To generate the full stacktrace, please run:
`./gradlew nexusIQScan --debug`

**Comment by guillermo-varela** [comment]
Issue https://github.com/sonatype-nexus-community/scan-gradle-plugin/issues/126 and PR https://github.com/sonatype-nexus-community/scan-gradle-plugin/pull/127 have been created to improve the error message.

**Comment by guillermo-varela** [comment]
Hi @cscrbuildhp 

Version 2.5.1 of this plugin improves the error message.

You can try using that version or still run `./gradlew nexusIQScan --stacktrace` to see a more detailed reason on why the plugin is not able to access your IQ Server instance.

**Comment by cscrbuildhp** [comment]
> Hi @cscrbuildhp
> 
> Version 2.5.1 of this plugin improves the error message.
> 
> You can try using that version or still run `./gradlew nexusIQScan --stacktrace` to see a more detailed reason on why the plugin is not able to access your IQ Server instance.

That did the trick, it was the organization ID was public name vice the ID itself. If developers integrate this they tend not to read the nuances of Org ID variable, 1) it must be the ID not the name, and 2) only used if application does not already exist.

Thanks for your help
