### ISSUE TITLE
The last 10 versions share a common transitive vulnerability in org.eclipse.jgit-5.8.1.202007141445-r.jar

### ISSUE THREAD

**Issue by rbhuet2** [sonatype-nexus-community/scan-gradle-plugin#152]
**Describe the bug****To Reproduce**
1. Run gradle build with any of the last 10 versions of the plugin defined.  For example:
   classpath "org.sonatype.gradle.plugins:scan-gradle-plugin:2.7.0"
   apply plugin: 'org.sonatype.gradle.plugins.scan'
2. See error
  Could not GET 'https://nexus.xxx.com/repository/public/org/eclipse/jgit/org.eclipse.jgit/5.8.1.202007141445-r/org.eclipse.jgit- 5.8.1.202007141445-r.jar'. Received status code 403 from server: -------------------->>> REQUESTED ITEM IS QUARANTINED -------------------->>>
**Expected behavior**
The plugin should reference a version of jgit that does not have any critical vulnerabilities.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Gradle Version: [7.4.2]
 - JVM Version and Flavor [Open JDK 17]
 - Nexus IQ Server Version: [166]

**Additional context**

**Comment by guillermo-varela** [comment]
Hi @rbhuet2!

From what I see, the JGit dependency comes from `nexus-platform-api`.

The latest version of `nexus-platform-api` already brings a JGit version without vulnerabilities, although upgrading that library brings a series of issues documented at #146 

While I can't provide a due date, I can confirm that such upgrade will definitely be done and thanks to this issue we see now it needs to have a higher priority.

Thanks for bringing this into our attention!

**Comment by rbhuet2** [comment]
I just tested version 2.8.1 and it works perfectly.  Thanks @shaikhu for the quick response!
