### ISSUE TITLE
[BUG] StackOverflowError

### ISSUE THREAD

**Issue by jwise-sncr** [sonatype-nexus-community/scan-gradle-plugin#161]
**Description**
When running the nexusIQScan task I receive a StackOverflowError with the following stack trace snippet:

Caused by: java.lang.StackOverflowError: (No message provided)
org.sonatype.gradle.plugins.scan.common.DependenciesFinder.fillAllChildDependencies (DependenciesFinder.java:432)
org.sonatype.gradle.plugins.scan.common.DependenciesFinder.fillAllChildDependencies (DependenciesFinder.java:436) org.sonatype.gradle.plugins.scan.common.DependenciesFinder.fillAllChildDependencies (DependenciesFinder.java:436)
org.sonatype.gradle.plugins.scan.common.DependenciesFinder.fillAllChildDependencies (DependenciesFinder.java:436)
...

**To Reproduce**
I'm working to create a minimal reproducer.  From the stack trace, it appears to be a circular dependency of some sort.

**Expected behavior**
A successful scan.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: OS X 14.4.1 (aarch64)
 - Gradle Version: 8.4
 - JVM Version and Flavor:  Amazon Corretto OpenJDK 64-Bit Server VM 17.0.11+9-LTS (mixed mode, sharing)
 - Nexus IQ Server Version: 174
 - Version: 2.8.2

**Additional context**

1. Appears this logic was introduced in 2.8.0.  Version 2.7.0 scans the same project successfully.
2. excludeCompileOnly = true

**Comment by guillermo-varela** [comment]
Version 2.8.3 includes a changes that might fix this issue, however it's only available through the Gradle plugins portal.
There is an error publishing to Central Repository that will be reviewing.

**Comment by guillermo-varela** [comment]
@jwise-sncr, version 2.8.3 has been now completely published.
Please check if that one works for you.

**Comment by jwise-sncr** [comment]
It works now.  Thank you!
