### ISSUE TITLE
[FEATURE] Have gradle build enforce/detect required jdk 8

### ISSUE THREAD

**Issue by bhamail** [sonatype-nexus-community/scan-gradle-plugin#18]
If you build with a new JDK, you may get errors that don't provide much clue about the underlying cause of the problem. For example, running:

```
./gradlew integrationTest
```
If your default JDK is say: 11, 
```
$ java -version
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)
```

you will see errors like this:

```
org.sonatype.gradle.plugins.scan.ScanIT_Gradle_Versions_4_2_to_4_4 > testAuditTask_Vulnerabilities_OssIndex[Version: 4.2.1] FAILED
    java.lang.IllegalStateException
        Caused by: org.gradle.tooling.GradleConnectionException
            Caused by: java.lang.IllegalArgumentException

```

What, you didn't recognize this as a JDK version issue right away? Me neither. ;)

* **How could we solve this issue? (Not knowing is okay!)**

I'm pretty sure there is a way to enforce JDK version in a Gradle build, not sure how though.

cc @bhamail / @DarthHater / @guillermo-varela

**Comment by guillermo-varela** [comment]
Usually this is how a JDK version is set for a Gradle build: https://github.com/sonatype-nexus-community/scan-gradle-plugin/blob/master/build.gradle#L26-L29

**Comment by bhamail** [comment]
I think that is only for the output of the compiler. It does not enforce the JDK version (nor javac version, etc).

**Comment by guillermo-varela** [comment]
> I think that is only for the source code spec and the output of the compiler. It does not enforce the JDK version (nor javac version, etc). I'm thinking about an equivalent to the Maven Enforcer plugin, eg: https://maven.apache.org/enforcer/enforcer-rules/requireJavaVersion.html

Maybe there is Gradle plugin for that, but you can try this:

```
if (JavaVersion.current() != project.targetCompatibility) {
    throw new GradleException("The java version used ${JavaVersion.current()} is not the expected version ${project.targetCompatibility}.")
}
```

**Comment by shaikhu** [comment]
> Maybe there is Gradle plugin for that, but you can try this on `build.gradle`:

http://kordamp.org/enforcer-gradle-plugin/
