### ISSUE TITLE
[FEATURE] ossIndexAudit - Show only dependencies with vulnerabilities

### ISSUE THREAD

**Issue by JamesMcMahon** [sonatype-nexus-community/scan-gradle-plugin#28]
* **What are you trying to do?**

I am trying to quickly scan my project for issues with `ossIndexAudit`. Right now the output shows every single scanned dependency, even if the number of vulnerabilities is 0.

* **What feature or behavior is this required for?**

Lower the signal to noise ratio and being able to quickly identify dependencies with issues

* **How could we solve this issue? (Not knowing is okay!)**

Not sure, I honestly could just be missing a flag, if so let me know and I will create a PR to add it to the README.

If this is a new feature I would suggest the current behavior would be better served as a verbose option.

* **Anything else?**

Happy to help implement if you are open to PRs.

cc @bhamail / @DarthHater / @guillermo-varela

**Comment by DarthHater** [comment]
Very into a PR!

In our other tools, we are starting to do exactly what you describe. We are making default behavior to just show what's vulnerable (if anything), a summary of what is scanned (total deps, and total vulnerable deps), and a flag like `--loud` to show everything (in case someone wants a holistic view of their project), if any of that helps!

**Comment by DarthHater** [comment]
Also @guillermo-varela would likely know if such a flag exists already, so I'm tagging him in here!

**Comment by guillermo-varela** [comment]
@JamesMcMahon, @JamesMcMahon The plugin still doesn't have such a flag, but a PR adding it would be welcomed :)

Please make sure it includes tests (specially [integration test](https://github.com/sonatype-nexus-community/scan-gradle-plugin/blob/master/src/integTest/java/org/sonatype/gradle/plugins/scan/ScanPluginIntegrationTestBase.java) to make sure the flag works with the supported Gradle versions) and update the README.md file documenting how to use the flag.

**Comment by guillermo-varela** [comment]
Hi @JamesMcMahon and @DarthHater 

Version 2.0.0 of this plugin has been published and now by default only dependencies with vulnerabilities will be printed.

To include the ones without vulnerabilities we added the new the property `showAll`. Please see https://github.com/sonatype-nexus-community/scan-gradle-plugin#oss-index for details.

Thanks.

**Comment by JamesMcMahon** [comment]
Amazing, thanks for the heads up!
