### ISSUE TITLE
[BUG] Android app configuration as described not working

### ISSUE THREAD

**Issue by aarongrider** [sonatype-nexus-community/scan-gradle-plugin#29]
**Describe the bug**
When adding to an android application, we get an error when running the nexusIQScan task

**To Reproduce**
1. Run './gradlew nexusIQScan'
2. See error

* What went wrong:
Execution failed for task ':nexusIQScan'.
> Could not resolve all dependencies for configuration ':app:releaseCompileClasspath'.
   > More than one variant of project :libraries:bypass:bypass matches the consumer attributes:
       - Configuration ':libraries:bypass:bypass:releaseApiElements' variant android-aidl:
           - Unmatched attributes:
               - Found artifactType 'android-aidl' but wasn't required.
               - Found com.android.build.api.attributes.VariantAttr 'release' but wasn't required.
               - Required org.jetbrains.kotlin.platform.type 'androidJvm' but no value provided.
           - Compatible attributes:
               - Required com.android.build.api.attributes.BuildTypeAttr 'release' and found compatible value 'release'.
               - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
               - Required org.gradle.usage 'java-api' and found compatible value 'java-api'.
       - Configuration ':libraries:bypass:bypass:releaseApiElements' variant android-manifest:
           - Unmatched attributes:
               - Found artifactType 'android-manifest' but wasn't required.
               - Found com.android.build.api.attributes.VariantAttr 'release' but wasn't required.
               - Required org.jetbrains.kotlin.platform.type 'androidJvm' but no value provided.
           - Compatible attributes:
               - Required com.android.build.api.attributes.BuildTypeAttr 'release' and found compatible value 'release'.
               - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
               - Required org.gradle.usage 'java-api' and found compatible value 'java-api'.
       - Configuration ':libraries:bypass:bypass:releaseApiElements' variant android-renderscript:
           - Unmatched attributes:
               - Found artifactType 'android-renderscript' but wasn't required.
               - Found com.android.build.api.attributes.VariantAttr 'release' but wasn't required.
               - Required org.jetbrains.kotlin.platform.type 'androidJvm' but no value provided.
           - Compatible attributes:
               - Required com.android.build.api.attributes.BuildTypeAttr 'release' and found compatible value 'release'.
               - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
               - Required org.gradle.usage 'java-api' and found compatible value 'java-api'.
       - Configuration ':libraries:bypass:bypass:releaseApiElements' variant android-symbol-with-package-name:
           - Unmatched attributes:
               - Found artifactType 'android-symbol-with-package-name' but wasn't required.
               - Found com.android.build.api.attributes.VariantAttr 'release' but wasn't required.
               - Required org.jetbrains.kotlin.platform.type 'androidJvm' but no value provided.
           - Compatible attributes:
               - Required com.android.build.api.attributes.BuildTypeAttr 'release' and found compatible value 'release'.
               - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
               - Required org.gradle.usage 'java-api' and found compatible value 'java-api'.

**Comment by guillermo-varela** [comment]
Possibly related to: https://github.com/gradle/gradle/issues/5426

**Comment by guillermo-varela** [comment]
This sample project allows to replicate the error: https://github.com/agent8261/BugArtifactory

**Comment by guillermo-varela** [comment]
@aarongrider Using the project sample I mentioned above I was able to make it work applying a couple of changes there after checking similar Gradle and Android bugs that have been reported elsewhere. Maybe those could work for your project as well:

1. Update the Android Gradle plugin to `com.android.tools.build:gradle:3.1.0` or newer on your root `build.gradle` file.
2.  As recommended on https://github.com/dialogflow/dialogflow-android-client/issues/57#issuecomment-341329755 change the way modules are imported as dependencies into others from:
    - `api project(':core')` or `implementation project(':core')` to
    - `api project(path: ':core', configuration: 'default')` or `implementation project(path: ':core', configuration: 'default')`
3. Not used on my tests: upgrade google services to `com.google.gms:google-services:4.0.1` as recommended on https://issuetracker.google.com/issues/79235243

Please let us know if any of that works so the plugin docs can be updated if necessary.

**Comment by ButterB0wl** [comment]
@aarongrider not sure if you saw this, but would appreciate your feedback on whether the above is feasible for our call later today :)

**Comment by aarongrider** [comment]
Trying it now!

**Comment by aarongrider** [comment]
Still not able to get it to work. Do you have a sample android project with this plugin installed that I can reference?

**Comment by aarongrider** [comment]
Yeah, that fixed it. Thanks.
