### ISSUE TITLE
[FEATURE] Add reference to example project in README.md

### ISSUE THREAD

**Issue by bhamail** [sonatype-nexus-community/scan-gradle-plugin#36]
Was looking for an example project to use in trying this plugin. Found this project via searching github: https://github.com/guillermo-varela/example-scan-gradle-plugin

It would be helpful if a link to this example project was added to the `scan-gradle-plugin` README.md file.

cc @bhamail / @DarthHater / @guillermo-varela

**Comment by guillermo-varela** [comment]
@bhamail That project was made during Innovation Week to test what I ended up sending to https://github.com/sonatype/iweek-scanner-hello/tree/master/intentionally-vulnerable-gradle-project

It might be worth asking @darylhandley if that "hello world" repo is officially ready.

**Comment by bhamail** [comment]
@guillermo-varela Cool. I already steered @mitunzavery to that project. Maybe @darylhandley can get Mitun to help validate the example project.

**Comment by guillermo-varela** [comment]
A reference to an updated repo with CI examples has been added: https://github.com/sonatype-nexus-community/scan-gradle-plugin#how-to-use
