### ISSUE TITLE
[BUG] The plugin cannot access the meta data when running behind a proxy

### ISSUE THREAD

**Issue by aburmeis** [sonatype-nexus-community/scan-gradle-plugin#40]
**Describe the bug**
The plugin cannot access the meta data from `ossindex.sonatype.org` when running behind a proxy without direct internet access.

**To Reproduce**
1. Configure a gradle build with the plugin
2. Configure a proxy in `gradle.properties` (`systemProp.https.proxyHost`, `systemProp.https.proxyPort`)
3. Run `./gradlew ossIndexAudit`
4. See error `Connection timed out`

**Expected behavior**
The Java system properties for Proxy settings should be applied so the meta data can be fetched from behind a proxy.

**Screenshots**
```
> Task :ossIndexAudit
Using anonymous request
Checking vulnerabilities in 120 dependencies

> Task :ossIndexAudit FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ossIndexAudit'.
> Could not audit the project: Connect to ossindex.sonatype.org:443 [ossindex.sonatype.org/3.128.15.143, ossindex.sonatype.org/18.218.3.80, ossindex.sonatype.org/3.133.173.34] failed: Operation timed out (Connection timed out)
```

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.5
 - Gradle Version: 6.4.1
 - JVM Version and Flavor: Open JDK 8
 - Version: 1.2.0

**Comment by ctmay4** [comment]
I am having the same issue.  Did you find a work-around?

**Comment by guillermo-varela** [comment]
Hi @aburmeis and @ctmay4 

Version 2.0.0 of this plugin has been published and proxy details can be set for accessing OSS Index using the property `proxyConfiguration`. Please see https://github.com/sonatype-nexus-community/scan-gradle-plugin#oss-index

Thanks.
