### ISSUE TITLE
[BUG] Android variants / dependency variants can not be resolved

### ISSUE THREAD

**Issue by Tangresh** [sonatype-nexus-community/scan-gradle-plugin#41]
**Describe the bug**
Android projects which use nested modules that are themselves full Android projects (with application variants) cause the dependency resolution to fail:
```
$ ./gradlew :app:nexusIQScan        
Configuration on demand is an incubating feature.
> Task :app:nexusIQScan FAILED
1 actionable task: 1 executed
<-------------> 0% WAITING
> :app:nexusIQScan > Resolve dependencies of :app:debugAndroidTestCompileClassp

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:nexusIQScan'.
> Could not resolve all dependencies for configuration ':app:debugAndroidTestCompileClasspath'.
   > More than one variant of project :commonlib matches the consumer attributes:
       - Configuration ':commonlib:debugApiElements' variant android-aidl:
           - Unmatched attributes:
               - Found artifactType 'android-aidl' but wasn't required.
               - Found com.android.build.api.attributes.VariantAttr 'debug' but wasn't required.
           - Compatible attributes:
               - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
               - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
               - Required org.gradle.usage 'java-api' and found compatible value 'java-api'.
               - Required org.jetbrains.kotlin.platform.type 'androidJvm' and found compatible value 'androidJvm'.
       - Configuration ':commonlib:debugApiElements' variant android-manifest:
           - Unmatched attributes:
               - Found artifactType 'android-manifest' but wasn't required.
               - Found com.android.build.api.attributes.VariantAttr 'debug' but wasn't required.
           - Compatible attributes:
               - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
               - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
               - Required org.gradle.usage 'java-api' and found compatible value 'java-api'.
               - Required org.jetbrains.kotlin.platform.type 'androidJvm' and found compatible value 'androidJvm'.
       - Configuration ':commonlib:debugApiElements' variant android-renderscript:
           - Unmatched attributes:
               - Found artifactType 'android-renderscript' but wasn't required.
               - Found com.android.build.api.attributes.VariantAttr 'debug' but wasn't required.
           - Compatible attributes:
               - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
               - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
               - Required org.gradle.usage 'java-api' and found compatible value 'java-api'.
               - Required org.jetbrains.kotlin.platform.type 'androidJvm' and found compatible value 'androidJvm'.
       - Configuration ':commonlib:debugApiElements' variant android-symbol-with-package-name:
           - Unmatched attributes:
               - Found artifactType 'android-symbol-with-package-name' but wasn't required.
               - Found com.android.build.api.attributes.VariantAttr 'debug' but wasn't required.
           - Compatible attributes:
               - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
               - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
               - Required org.gradle.usage 'java-api' and found compatible value 'java-api'.
               - Required org.jetbrains.kotlin.platform.type 'androidJvm' and found compatible value 'androidJvm'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

**To Reproduce**
1. Checkout sample project: https://github.com/inventage/iqserver-android
2. Copy `app/gradle.template.properties` to `app/gradle.properties` and set nexusIQServer properties
3. Run `./gradlew :app:nexusIQScan`

**Expected behavior**
I expect the dependencies of the module `app` to be gathered and submitted for a scan.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Gradle Version: 5.6.4 (Gradle Wrapper)
 - JVM Version and Flavor: OpenJDK, Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
 - Nexus IQ Server Version: 93
 - Version 1.2.0

**Additional context**
The problem is related to Gradle's concept of dependency variants. The Android build system uses it heavily, but the problem is not exclusive to Android submodules, it also shows up when using dependencies that are published with Gradle variant metadata and having the experimental metadata feature enabled.

Not all resolvable configurations have enough metadata to determine which variants of dependencies should be selected and the ones that do in an Android project might not contain jars/aars anymore. We could not find a single existing configuration that is both *actually* resolvable and contains the aars we need to successfully scan. There is a way to extract the actual compile classpath of a single variant (see https://proandroiddev.com/how-to-extract-your-android-projects-dependencies-with-a-gradle-task-1775e8c21093 and https://gist.github.com/n-belokopytov/d44949590748b096c1a497008b761d04) that was also at one point featured on the Sonatype blog, but that yields just the contained jars of any aars that an Android build might use as dependency.

We managed to extract the full set of dependencies eventually, with our custom Gradle plugin in the referenced sample project. (see https://github.com/inventage/iqserver-android/blob/master/buildSrc/src/main/java/com/inventage/gradle/android/AndroidResolvableConfigPlugin.java)
The plugin works like this:
1. Create a new configuration in the build, that configuration is to be used to gather dependencies for the scan.
2. For all dependencies added to a set of existing configurations (including extended configurations):
  1. If the dependency is to another Gradle module, repeat this algorithm for that module, starting at step 2
  2. If the dependency is anything else, add the dependency to our new configuration
Then in the build, add a Copy task that copies the contents of our configuration to a directory we went. Externally to the build, scan the directory with the iq server CLI.
For external dependencies with variants, it is necessary to add Attributes to our configuration to help Gradle select the dependency variant. That is now hardcoded to "org.gradle.usage" -> "java-runtime", but might have to be configurable.

It would be great to see this adapted algorithm included in the Sonatype plugin.

This is probably related to https://github.com/sonatype-nexus-community/scan-gradle-plugin/issues/32 in that our method uses separate Configurations and a Copy task to copy dependencies instead of resolving them 'manually' in the plugin.

**Comment by guillermo-varela** [comment]
Errors due to variants usage, similar to #31

**Comment by guillermo-varela** [comment]
Hi @Tangresh,

Thanks for your sample code :)

I got the chance to play with it. I found that more than the algorithm you mentioned to collect the dependencies in using recursion in `copyReleaseCompileClasspathDependencies` based on `ProjectDependency` the real trick is having the new configuration with `"org.gradle.usage" -> "java-runtime"` as without that part the end result is the same error as our current plugin throws.

Resolving the variants problem using the usage value is something we need to think carefully as the values in the constant for that setting has been changing a lot: https://docs.gradle.org/current/javadoc/org/gradle/api/attributes/Usage.html#JAVA_RUNTIME

That interface exists since Gradle 3.4, but the current values have been there only since 4.0 (values from older versions were deleted so no backward compatibility) and this plugin includes support for Gradle 3.3.

While we take a closer look, a workaround I was able to test is:
- Move the applying of this plugin to the root `build.gradle`.
- Change how the dependency of `commonlib` is declared from `implementation project(path: ':commonlib')` to `implementation project(path: ':commonlib', configuration: 'default')`.

**Comment by guillermo-varela** [comment]
Hi @Tangresh 

Version 2.0.0 of this plugin has been published and your sample project was scanned and evaluated without errors. Please give it a try.

Thanks.

**Comment by JCreswellENVRMNT** [comment]
> Hi @Tangresh,
> 
> Thanks for your sample code :)
> 
> I got the chance to play with it. I found that more than the algorithm you mentioned to collect the dependencies using recursion in `copyReleaseCompileClasspathDependencies` based on `ProjectDependency` the real trick is having the new (temporal) configuration with `"org.gradle.usage" -> "java-runtime"` as without that part the end result is the same error as our current plugin throws.
> 
> Resolving the variants issue using the usage attribute is something we need to think carefully as the values in the constant for that setting has been changing a lot: https://docs.gradle.org/current/javadoc/org/gradle/api/attributes/Usage.html#JAVA_RUNTIME
> 
> That interface exists since Gradle 3.4, but the current values have been there only since 4.0 (values from older versions were deleted so no backward compatibility) and this plugin includes support for Gradle 3.3.
> 
> While we take a closer look, a workaround I was able to test is:
> 
> * Move the applying of this plugin to the root `build.gradle`.
> * Change how the dependency of `commonlib` is declared from `implementation project(path: ':commonlib')` to `implementation project(path: ':commonlib', configuration: 'default')`.

Hello, I'm hitting this issue from a different plugin and found that changing the project dependency to have a configuration: 'default' param per your suggestion does in fact work around it -- my questions is why does this help?  I haven't been able to find coherent documentation on what exactly the configuration param for the project dependency DSL does, and what concerns/considerations there might be when adding it with the value 'default'.

**Comment by guillermo-varela** [comment]
> I'm hitting this issue from a different plugin and found that changing the project dependency to have a configuration: 'default' param per your suggestion does in fact work around it -- my questions is why does this help? I haven't been able to find coherent documentation on what exactly the configuration param for the project dependency DSL does, and what concerns/considerations there might be when adding it with the value 'default'.

Quite late to the party, but the most helpful reference I was able to find was:
https://stackoverflow.com/a/19941894
