### ISSUE TITLE
[FEATURE] Vulnerability exclusions configuration

### ISSUE THREAD

**Issue by pctF** [sonatype-nexus-community/scan-gradle-plugin#58]
* **What are you trying to do?**
Some components will have vulnerabilities that not affect developed application or impact lowered to acceptable by environmental metrics. In this case it is common case to leave _vulnerable_ dependency in place. As I can see current DefaultResponseHandler for Oss Index Audit is not ready to handle exclusions so any dependency that should be ignored in individual application will fail build every time.
* **What feature or behavior is this required for?**
Way to pass exclusions meant to be ignored.
* **How could we solve this issue? (Not knowing is okay!)**
Implementing vulnerability filter used by response handlers throwing away entries. 

cc @bhamail / @DarthHater / @guillermo-varela

**Comment by nihaf** [comment]
I believe this is a crucial enhancement as it's already an existing feature of the OSS Index Maven plugin (see https://sonatype.github.io/ossindex-maven/maven-plugin/excludes/).

**Comment by pctF** [comment]
It defenetly is. 
Right now this plugin has amazing feature I actually couldn't find in ANY free sca (left shift, i believe has something similar but couldn't get my hands on it) gradle tool - build break if vulnarable dependencies detected. It is just amazing thing to automate rules for pipeline. But without exclusion rules it couldn't be implemented for automatisation.

**Comment by guillermo-varela** [comment]
Hi @pctF and @nihaf 

Version 2.0.1 has been published adding `excludeCoordinates` and `excludeVulnerabilityIds` to support exclusions :)

**Comment by pctF** [comment]
@guillermo-varela thanks a lot. Sorry for lack of collaboration on this one - you was impressively fast on this one

**Comment by DarthHater** [comment]
@guillermo-varela and @shaikhu rule!
