### ISSUE TITLE
Update dependencies to support latest java versions

### ISSUE THREAD

**Issue by eirnym** [sonatype-nexus-community/scan-gradle-plugin#66]
Please, update dependencies as security scan you included (1.3.0) doesn't support Java 14+, while later version (1.6.0) does.

Also please update other dependencies if possible.

cc @bhamail / @DarthHater / @guillermo-varela / @shaikhu

**Comment by guillermo-varela** [comment]
Hi @eirnym,

> Please, update dependencies as security scan you included (1.3.0) doesn't support Java 14+, while later version (1.6.0) does.
We're looking into this.

> Also please update other dependencies if possible.
The plugin only has 2 direct dependencies (one for OSS Index and other for Nexus IQ Server) and as we're shadowing/shading the final JAR you should not be getting classpath clashes when using the plugin :)

**Comment by eirnym** [comment]
It's great! Could you also upgrade gradle to 6.8.2 with shadow plugin as well. It turns out, that this plugin could be compatible with 5.6+ as I saw in my plugin as well

**Comment by guillermo-varela** [comment]
> It's great! Could you also upgrade gradle to 6.8.2

Do you mean updating the plugin to be built using that Gradle version or the plugin supporting projects using that version?

**Comment by eirnym** [comment]
I mean if you build with later version of Gradle you won't break compatibility if ABI is the same. Currently with Gradle 6.8.2 ABI is the same as Gradle 5.6.x, so you can upgrade your plugin leaving the compatibility. I have a test in my plugin to make sure that ABI is compatible for these versions.

If you worry about compatibility of earlier versions of gradle, I'm not sure if users want to have newer version of underlaying library as well (it could be incompatible).

**Comment by guillermo-varela** [comment]
Hi @eirnym 

Version 2.0.7 has been published with all dependencies and Gradle version updated.

Please give it a try :)
