### ISSUE TITLE
[FEATURE] results in a file

### ISSUE THREAD

**Issue by bguedel** [sonatype-nexus-community/scan-gradle-plugin#67]
* **What are you trying to do?**
Save the results with my build in json format

* **What feature or behavior is this required for?**
Internal build verification.

* **How could we solve this issue? (Not knowing is okay!)**
Currently it looks like you "accept" the [results path](https://github.com/sonatype-nexus-community/scan-gradle-plugin/blob/master/src/main/java/org/sonatype/gradle/plugins/scan/nexus/iq/NexusIqPluginExtension.java#L29) but I dont think you actually use it?

* **Anything else?**

cc @bhamail / @DarthHater / @guillermo-varela / @shaikhu

**Comment by guillermo-varela** [comment]
Hi @bguedel 

Certainly we don't seem to use that field at all 😕
We'll try to remember what was the intention for it and see if it fits with your requirement.

Just one question: since the field you reference is for Nexus Lifecycle (IQ Server), what do you expect to save in a JSON file? The result of the scan and evaluation are stored as a report in IQ Server and are no part of this plugin output. Maybe you really mean saving the output for OSS Index?

**Comment by guillermo-varela** [comment]
After a deeper inspection, the field `resultFilePath` was added initially to support the same JSON file storage being done for the Maven plugin: https://help.sonatype.com/integrations/sonatype-clm-for-maven#SonatypeCLMforMaven-EvaluatingProjectComponentswithNexusIQServer

We'll check if it's possible to have that feature in this plugin as well.

**Comment by galet** [comment]
Unfortunately this makes it difficult for us to use it properly in our CI pipeline (TeamCity). Parsing console output to get a scan ID and getting the data via REST API is certainly an option however completely unusable for our complex environment. Any ETA?

**Comment by DarthHater** [comment]
@galet the team tends to work on this every two weeks, no guarantee but I'd imagine they may be taking a look at it tomorrow.

**Comment by guillermo-varela** [comment]
Hi @galet and @bguedel 

As @DarthHater said we hope to make significant progress on this tomorrow, but knowing that this feature is truly needed helps us to prioritize this issue higher up, so your comments are deeply appreciated :)

Thanks.

**Comment by guillermo-varela** [comment]
Hi @galet and @bguedel 

Just to give you an update, we hit a roadblock related to a library this plugin depends on. Hopefully for our next iteration we can continue to work on this, as now we have a clear idea on how to add this feature.


Thanks.

**Comment by bguedel** [comment]
Sorry, havent been checking the issue; thanks for the response. Looking forward to seeing if this can be accomplished.

**Comment by guillermo-varela** [comment]
Hi @galet and @bguedel 

Early tests on a [draft PR](https://github.com/sonatype-nexus-community/scan-gradle-plugin/pull/70) look promising, when more comprehensive tests can be made a new version will be published.

Thanks.

**Comment by guillermo-varela** [comment]
Hi @bguedel and @galet

Version 2.0.6 has been published and includes this feature!

Please give it try :)

**Comment by galet** [comment]
@guillermo-varela, works great. Thank you!

**Comment by bguedel** [comment]
Works for me!! thanks!
