### ISSUE TITLE
Error updating to 2.0.4

### ISSUE THREAD

**Issue by ctmay4** [sonatype-nexus-community/scan-gradle-plugin#68]
If I update from 2.0.3 to 2.0.4, I get errors compiling the build.gradle.

```
A problem occurred evaluating root project 'seerapi'.
> No signature of method: build_1uysbcvuf4za1zy75np46yxee.ossIndexAudit() is applicable for argument types: (build_1uysbcvuf4za1zy75np46yxee$_run_closure6) values: [build_1uysbcvuf4za1zy75np46yxee$_run_closure6@6938ff10]
```

I made no other changes to build.gradle except changing the version.  If I go back to 2.0.3 it works fine again.

Here is my config in build.gradle.

The plugin:

```
plugins {
    // snipped
    id 'org.sonatype.gradle.plugins.scan' version '2.0.4'
}

```

the config

```groovy
ossIndexAudit {
    printBanner = false
    dependencyGraph = true
    proxyConfiguration {
        protocol = 'http'
        host = 'webproxy-btp.imsweb.com'
        port = 8080
    }
}
```

I didn't see any changes in the documentation.  Did the configuration instructions change?

**Comment by guillermo-varela** [comment]
Hi @ctmay4 

There is a pull request to address this: https://github.com/sonatype-nexus-community/scan-gradle-plugin/pull/69
However it requires more tests before we can merge it and publish a new version.

Thanks for bringing this to our attention.

**Comment by ctmay4** [comment]
Great!  Thanks.

**Comment by guillermo-varela** [comment]
Hi @ctmay4 

A new version has been published with this fix: https://github.com/sonatype-nexus-community/scan-gradle-plugin/releases/tag/2.0.5

Please give it a try :)

Thanks.

**Comment by ctmay4** [comment]
Working well for me now.  Thanks for the fix!
