### ISSUE TITLE
[FEATURE] Automatize publishing

### ISSUE THREAD

**Issue by guillermo-varela** [sonatype-nexus-community/scan-gradle-plugin#7]
* **What are you trying to do?**
Eliminate the need to manually publish the plugin.

* **What feature or behavior is this required for?**
The plugin will be published both on Maven Central and [Gradle Plugin Portal](https://plugins.gradle.org/) (using an account for the organization, not a personal one). Doing this from a local dev environment is not quite convenient, considering that now we're using CircleCI.

- [x] Publish on Maven Central
- [x] Gradle Plugin Portal

* **How could we solve this issue? (Not knowing is okay!)**
https://guides.gradle.org/publishing-plugins-to-gradle-plugin-portal/

* **Anything else?**
No

**Comment by guillermo-varela** [comment]
@bhamail  the code looks good!

The only question I have is if the account on the Gradle Plugins site was created using an email alias or list for Integrations/Plugins/etc team or your personal Sonatype email address. On the later case, only you would be able to read both key and secret and not the rest of the team.

**Comment by bhamail** [comment]
Victory! I verified using a new release (0.2.19) that both Central:
https://repo1.maven.org/maven2/org/sonatype/gradle/plugins/scan-gradle-plugin/0.2.19/

and Gradle Plugin Portal:
https://plugins.gradle.org/plugin/org.sonatype.gradle.plugins.scan

have the new release. Joy!

Currently, anyone with permissions can run the [release](https://circleci.com/gh/sonatype-nexus-community/workflows/scan-gradle-plugin) workflow to perform a release.
