### ISSUE TITLE
Provide example for Gradle's Kotlin DSL

### ISSUE THREAD

**Issue by rgmz** [sonatype-nexus-community/scan-gradle-plugin#71]
* **What are you trying to do?**
Configure my `build.gradle.kts` file to perform a scan.

* **What feature or behavior is this required for?**

* **How could we solve this issue? (Not knowing is okay!)**
Provide an example of how to configure the plugin for both `build.gradle` and `build.gradle.kts`. 

    There isn't a clear path to translate Groovy to Kotlin, which is a general Gradle issue. I'll open a PR if I have time to figure this out myself.

* **Anything else?**

cc @bhamail / @DarthHater / @guillermo-varela / @shaikhu

**Comment by rgmz** [comment]
Changes required to get it working:
* replace single quotes (`'`) with double-quotes (`"`)
* replace booleans like `allConfigurations` to `isAllConfigurations = true` (Kotlin prefixes boolean properties with `is`)

**Comment by guillermo-varela** [comment]
> I'll open a PR if I have time to figure this out myself.

PRs are welcome :)

**Comment by josevnz** [comment]
Hello, I created a pull request with an update to shown the syntax in Kotlin as well. Can you take a look and let me know what you think? https://github.com/sonatype-nexus-community/scan-gradle-plugin/pull/104

**Comment by josevnz** [comment]
Also signed the CLA!

**Comment by guillermo-varela** [comment]
> Also signed the CLA!

Hi @josevnz!

Cross posting for visibility of https://github.com/sonatype-nexus-community/scan-gradle-plugin/pull/104#issuecomment-1018730250

I see the commit was done using the account @kodegeek which I believe is also yours.
If that's the case, please sign the CLA using the @kodegeek account as well.

Thanks.

**Comment by kodegeek** [comment]
Hello guys,

I lost access to that account. Because I own two I think Hithub is confused.

I asked support to delete Kodegeek but not sure when it will be done 

Really sorry about that.

There is a way to change this or should I try to do a new pull request?

**Comment by guillermo-varela** [comment]
You can try opening a new PR, just make sure the commit and the PR are created with a GitHub account that can sign the CLA.

**Comment by kodegeek** [comment]
Yeah let me do that. I think I messed up with the ssh keys I used to push the commit. Let’s do this, cancel this pull request and I will do a new one.

Thanks!

**Comment by josevnz** [comment]
Hello all,

I created a new pull request (#105) and looks clean. Feel free to check and see if this can be merged into the trunk.

Thanks!

**Comment by josevnz** [comment]
Finally, one that works: #106 
Thanks!

**Comment by josevnz** [comment]
> #106

Hello Guillermo, did you got a chance to check #106?

Thanks!

**Comment by guillermo-varela** [comment]
Hi @josevnz,

I love your enthusiasm :)

Although it usually takes me some time to be able to check back PRs on community projects, #106 was easy enough to review and it has been approved and merged.

Thank you for contributing!

**Comment by josevnz** [comment]
Epic! Thanks a lot. Happy to contribute to a great tool.
Jose Vicente Nunez 

    On Tuesday, January 25, 2022, 10:04:42 AM EST, Guillermo Varela ***@***.***> wrote:  
 
 


Hi @josevnz,

I love your enthusiasm :)

Although it usually takes me some time to be able to check back PRs on community projects, #106 was easy enough to review and it has been approved and merged.

Thank you for contributing!
