### ISSUE TITLE
[FEATURE] Scan Targets instead of Configurations

### ISSUE THREAD

**Issue by jwise-sncr** [sonatype-nexus-community/scan-gradle-plugin#81]
* **What are you trying to do?**
Currently the Gradle plugin harvests dependencies from Gradle configurations.  Instead I'd like the plugin to scan the artifacts of the build (ie jar, war, ear, etc).

* **What feature or behavior is this required for?**
Allows NexusIQ CLI style behavior from a Gradle build instead of having to download and run the CLI independently.

* **How could we solve this issue? (Not knowing is okay!)**
Provide a `targets` property in the extension that defaults to empty.  Specifying it would turn off configuration scanning and only scan the specified targets of the build.  `targets` property should be considered a task input for incremental builds.

* **Anything else?**
Plugin scan task must occur during check lifecycle task (after assemble lifecycle task) so that artifacts are available for scanning although hooking jar, etc task outputs to scan task inputs may be sufficient.

cc @bhamail / @DarthHater / @guillermo-varela / @shaikhu

**Comment by guillermo-varela** [comment]
Hi @jwise-sncr,

What is the expected benefit of scanning the built artifact rather than the dependencies from the Gradle configurations?

**Comment by jwise-sncr** [comment]
@guillermo-varela,

Guarantee that you're only reporting on what is deployed to production.  If it isn't in the built artifact, it won't get into production.

**Comment by guillermo-varela** [comment]
@jwise-sncr,

I'm curious, under which scenario dependencies that are under the Gradle compile and runtime configurations would not end up in the built artifact for production?

**Comment by jwise-sncr** [comment]
@guillermo-varela,

In a multi-project build where one or more of the projects contain only test suites or a test library.  These test projects use the compile configuration, but are referenced in the testCompile configuration of other projects within the multi-project build.  The test sub-projects are never published nor deployed.

**Comment by guillermo-varela** [comment]
@jwise-sncr,

Since this is an issue more related to sub-projects, would it be good enough for your use case to have a configuration that allows to exclude sub-projects by name?

That way you could still apply the plugin at root/parent level without scanning the test sub-modules.

**Comment by jwise-sncr** [comment]
@guillermo-varela,

Yes, that approach would be satisfactory.

**Comment by guillermo-varela** [comment]
@jwise-sncr,

The setting to allow excluding modules from NexusIQ evaluation has been added in version 2.1.0: https://github.com/sonatype-nexus-community/scan-gradle-plugin/releases/tag/2.1.0


Thanks.

**Comment by jwise-sncr** [comment]
@guillermo-varela,

Thanks!
