### ISSUE TITLE
[FEATURE]Support resultFilePath in ossIndexAudit

### ISSUE THREAD

**Issue by robjerdonek** [sonatype-nexus-community/scan-gradle-plugin#94]
* **What are you trying to do?**
Store the scan results in a JSON file when using ossIndexAudit
* **What feature or behavior is this required for?**
It would be easier to parse the ossIndexAudit scan results if they were returned in a JSON file format.

* **How could we solve this issue? (Not knowing is okay!)**
The nexusIQScan already supports this setting.  Add a similar setting to ossIndexAudit.

* **Anything else?**

cc @bhamail / @DarthHater / @guillermo-varela / @shaikhu

**Comment by guillermo-varela** [comment]
Hi @robjerdonek,

We checked with @DarthHater and although there is no official schema for JSON outputs for OSS Index plugins, it is possible to provide such feature for this plugin.

For reference, here is how Nancy prints its output: https://github.com/sonatype-nexus-community/nancy#output

Thanks for bringing this into our attention :)

**Comment by DarthHater** [comment]
Given Gradle output is noisy, I think this makes sense. The nancy schema isn't like "set in stone", it's just what we arrived at over there. If you figure out a better way of doing things, go for it!

**Comment by guillermo-varela** [comment]
An example of CycloneDX 1.4 using JSON:
https://github.com/CycloneDX/specification/blob/master/tools/src/test/resources/1.4/valid-vulnerability-1.4.json

**Comment by guillermo-varela** [comment]
This feature has been published on version 2.4.0
https://github.com/sonatype-nexus-community/scan-gradle-plugin/releases/tag/2.4.0
